# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmultinom <- function(x, prob) {
    .Call('_ploidyverseClasses_dmultinom', PACKAGE = 'ploidyverseClasses', x, prob)
}

dDirichletMultinom <- function(x, prob, alpha) {
    .Call('_ploidyverseClasses_dDirichletMultinom', PACKAGE = 'ploidyverseClasses', x, prob, alpha)
}

nGen <- function(ploidy, nalleles) {
    .Call('_ploidyverseClasses_nGen', PACKAGE = 'ploidyverseClasses', ploidy, nalleles)
}

enumerateGenotypes <- function(ploidy, nalleles) {
    .Call('_ploidyverseClasses_enumerateGenotypes', PACKAGE = 'ploidyverseClasses', ploidy, nalleles)
}

indexGenotype <- function(genotype) {
    .Call('_ploidyverseClasses_indexGenotype', PACKAGE = 'ploidyverseClasses', genotype)
}

genotypeFromIndex <- function(index, ploidy) {
    .Call('_ploidyverseClasses_genotypeFromIndex', PACKAGE = 'ploidyverseClasses', index, ploidy)
}

alleleCopy <- function(genotype, nalleles) {
    .Call('_ploidyverseClasses_alleleCopy', PACKAGE = 'ploidyverseClasses', genotype, nalleles)
}

makeGametes <- function(genotype) {
    .Call('_ploidyverseClasses_makeGametes', PACKAGE = 'ploidyverseClasses', genotype)
}

selfingMatrix <- function(ploidy, nalleles) {
    .Call('_ploidyverseClasses_selfingMatrix', PACKAGE = 'ploidyverseClasses', ploidy, nalleles)
}

